### ISSUE TITLE
Update to the latest Godot-cpp to keep up with the latest GDExtension?

### ISSUE THREAD

**Issue by GeorgeS2019** [j20001970/GDMP#18]
> Is there a specific version of godot-cpp that should be used?
https://github.com/j20001970/GDMP/pull/14#issuecomment-1557061453

Is there necessary to have TWO repos. one for Godot3 and the other for Godot4? Since both have different GDExtension technology

There have been lots of GDExtension activities in Godot-cpp last one to two weeks
Do consider updating. Await feedback
![image](https://github.com/j20001970/GDMP/assets/49812372/7c518e76-17a0-451b-89bc-20c05b37ed47)

**Comment by j20001970** [comment]
I believe current `master` branch of godot-cpp is targeting in-development Godot 4.1, which is incompatible with GDExtension for Godot 4.0, as I tried to build the library with updated submodule then ended up with error message about incompatible version in editor about a week ago.

Since we are still targeting 4.0.x, we should stay at current submodule commit before moving on to 4.1
