### ISSUE TITLE
Build GDMP AAR

### ISSUE THREAD

**Issue by Niko-shvets** [j20001970/GDMP#5]
Hi!

thank you for the project, it is very interesting, but can you pls describe in more detail what I should do in step number 5. I am not very familiar with android that's why it is not obvious to me.

Thank you in advance,
Best

**Comment by j20001970** [comment]
Hi, for building GDMP aar, there should be a [android](https://github.com/j20001970/GDMP/tree/master/android) directory that is a Android Studio project, you should copy or symlink both godot-lib and mediapipe_aar built from step 3 to `android/GDMP/libs` as dependencies. Then build GDMP AAR using Android Studio (or just run gradlew build), it should located in `android/GDMP/build/outputs/aar` after build complete.

godot-lib AAR can be downloaded from [godotengine website](https://godotengine.org/download) or copy/symlink from your project's android build template (located in `android/build/release`)

**Comment by j20001970** [comment]
Hi @Niko-shvets , I updated the process of building GDMP aar and its instructions in README a while ago, now it should be simpler to build AAR since commit [9cb3792](https://github.com/j20001970/GDMP/commit/9cb379211ff26c407d94b92bb77f1267bc122587).
I will close the issue for now, feel free to reopen if you have further questions on build GDMP Android plugin.
